import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav/nav-bar";
const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OpenVMS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Navbar />
        <div className="mx-[1%]"> {children}</div>
      </body>
    </html>
  );
}
